spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
integration:
  user-service:
    url: http://localhost:8081